### PR TITLE
support for new flutter with v3.0.0

### PR DESCRIPTION
**Pull request by Nytrm**

### CODE REVIEW

**Comment by ArcticZeroo** [comment]
What does this have to do with new flutter? This just looks like a behavior change

**Comment by Nytrm** [comment]
my bad that must have slipped in, removed the state change logic.

**Comment by Nytrm** [comment]
I do have a bug that after clearing the search the ui state is not updated and the searchbar does not go away.

**Comment by Nytrm** [comment]
can this be merged? so we can continue using this with null safety versions (instead of a dev version)

**Comment by ArcticZeroo** [comment]
Sorry, this dropped off the radar. Will look at this and merge in the morning. I think it's probably time to archive this repo after the update, I don't have too much bandwidth :(

**Comment by ArcticZeroo** [comment]
I don't think there's any reason that we need to drop support for 2.12, going to just drop the -dev release

**Comment by ArcticZeroo** [comment]
Thanks for the contribution - I've just gone and made the changes directly. 3.0.0 is now released.

**Pull request closed without merging**
